
library(tm)
library(XML)

library(wordcloud)
library(RColorBrewer)
library(caret)
library(NLP)
library(openNLP)
library(RWeka)
library(qdap)
library(ggplot2)
library(stringi)
library(stringr)
library(magrittr)
library(SnowballC)
library(textcat)

load("Ngrams.RData")
source("predFn.R")